/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class App {
    public static void main(String[] args) {
        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);

        Runnable task = new StockPriceFetcher()::fetchAndPrintStockPrice;
        executor.scheduleAtFixedRate(task, 0, 5, TimeUnit.SECONDS);
    }
}
